name: creador_modular
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

# Dependencies 
dependencies:
  archive: ^3.6.1
  cupertino_icons: ^1.0.8
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  get: ^4.6.6
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.3.2

dev_dependencies:
  change_app_package_name: ^1.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  # change_app_package_name: ^1.3.0
  flutter_test:
    sdk: flutter

# In Terminal run:
# flutter clean && flutter pub get && flutter pub run flutter_launcher_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFFFF"
  adaptive_icon_foreground: "assets/logo_foreground.png"


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

